/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wordle;

/**
 *
 * @author matti
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jPanelParola = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelA = new javax.swing.JLabel();
        jLabelA1 = new javax.swing.JLabel();
        jLabelA2 = new javax.swing.JLabel();
        jLabelA3 = new javax.swing.JLabel();
        jLabelA4 = new javax.swing.JLabel();
        jLabelA5 = new javax.swing.JLabel();
        jLabelA6 = new javax.swing.JLabel();
        jLabelA7 = new javax.swing.JLabel();
        jLabelA8 = new javax.swing.JLabel();
        jLabelA9 = new javax.swing.JLabel();
        jLabelA10 = new javax.swing.JLabel();
        jLabelA11 = new javax.swing.JLabel();
        jLabelA12 = new javax.swing.JLabel();
        jLabelA13 = new javax.swing.JLabel();
        jLabelA14 = new javax.swing.JLabel();
        jLabelA15 = new javax.swing.JLabel();
        jLabelA16 = new javax.swing.JLabel();
        jLabelA17 = new javax.swing.JLabel();
        jLabelA18 = new javax.swing.JLabel();
        jLabelA19 = new javax.swing.JLabel();
        jLabelA20 = new javax.swing.JLabel();
        jLabelA21 = new javax.swing.JLabel();
        jLabelA22 = new javax.swing.JLabel();
        jLabelA23 = new javax.swing.JLabel();
        jLabelA24 = new javax.swing.JLabel();
        jLabelA25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setPreferredSize(new java.awt.Dimension(685, 685));

        jPanelParola.setBackground(new java.awt.Color(255, 255, 255));
        jPanelParola.setMinimumSize(new java.awt.Dimension(400, 400));
        jPanelParola.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanelParola.setLayout(new java.awt.GridLayout(5, 5));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("WORDLE");

        jLabelA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA.setText("A");

        jLabelA1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA1.setText("B");

        jLabelA2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA2.setText("C");

        jLabelA3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA3.setText("D");

        jLabelA4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA4.setText("E");

        jLabelA5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA5.setText("F");

        jLabelA6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA6.setText("G");

        jLabelA7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA7.setText("G");

        jLabelA8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA8.setText("G");

        jLabelA9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA9.setText("G");

        jLabelA10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA10.setText("G");

        jLabelA11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA11.setText("G");

        jLabelA12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA12.setText("G");

        jLabelA13.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA13.setText("G");

        jLabelA14.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA14.setText("G");

        jLabelA15.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA15.setText("G");

        jLabelA16.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA16.setText("G");

        jLabelA17.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA17.setText("G");

        jLabelA18.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA18.setText("G");

        jLabelA19.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA19.setText("G");

        jLabelA20.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA20.setText("G");

        jLabelA21.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA21.setText("G");

        jLabelA22.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA22.setText("G");

        jLabelA23.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA23.setText("G");

        jLabelA24.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA24.setText("G");

        jLabelA25.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelA25.setText("G");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jPanelParola, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelA1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelA2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelA3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelA4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelA5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelA6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelA7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelA8))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabelA23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelA12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelA24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelA13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelA18)
                                .addGap(4, 4, 4)
                                .addComponent(jLabelA14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelA15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabelA21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelA20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelA19, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabelA9)
                                .addGap(25, 25, 25)
                                .addComponent(jLabelA16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelA17))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabelA25)
                                .addGap(37, 37, 37)
                                .addComponent(jLabelA22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelA10)
                                .addGap(27, 27, 27))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelA11)
                        .addGap(140, 140, 140)))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelParola, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelA2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelA1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelA3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelA4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelA5)
                            .addComponent(jLabelA6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelA7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelA8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelA9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelA16)
                            .addComponent(jLabelA17))
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelA19)
                            .addComponent(jLabelA20)
                            .addComponent(jLabelA21)
                            .addComponent(jLabelA22)
                            .addComponent(jLabelA25)
                            .addComponent(jLabelA23)
                            .addComponent(jLabelA10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelA15)
                            .addComponent(jLabelA14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelA13)
                            .addComponent(jLabelA12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelA11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelA24)
                            .addComponent(jLabelA18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelA;
    private javax.swing.JLabel jLabelA1;
    private javax.swing.JLabel jLabelA10;
    private javax.swing.JLabel jLabelA11;
    private javax.swing.JLabel jLabelA12;
    private javax.swing.JLabel jLabelA13;
    private javax.swing.JLabel jLabelA14;
    private javax.swing.JLabel jLabelA15;
    private javax.swing.JLabel jLabelA16;
    private javax.swing.JLabel jLabelA17;
    private javax.swing.JLabel jLabelA18;
    private javax.swing.JLabel jLabelA19;
    private javax.swing.JLabel jLabelA2;
    private javax.swing.JLabel jLabelA20;
    private javax.swing.JLabel jLabelA21;
    private javax.swing.JLabel jLabelA22;
    private javax.swing.JLabel jLabelA23;
    private javax.swing.JLabel jLabelA24;
    private javax.swing.JLabel jLabelA25;
    private javax.swing.JLabel jLabelA3;
    private javax.swing.JLabel jLabelA4;
    private javax.swing.JLabel jLabelA5;
    private javax.swing.JLabel jLabelA6;
    private javax.swing.JLabel jLabelA7;
    private javax.swing.JLabel jLabelA8;
    private javax.swing.JLabel jLabelA9;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanelParola;
    // End of variables declaration//GEN-END:variables
}
